name: First Workflow
on: workflow_dispatch
jobs:
  first-action:
    runs-on: ubuntu_latest
    steps:
    - name: Print output
      run: echo "First Hello"
    - name: Complete job
      run: "Good bye!"
